### ISSUE TITLE
Makefile diffing needs to be desemverified

### ISSUE THREAD

**Issue by keirog** [Financial-Times/next-code-ombudsman#9]
![makefile-diff](https://cloud.githubusercontent.com/assets/150157/22883650/13e971d2-f1e9-11e6-8fc7-14c84fc7a93d.png)

**Comment by wheresrhys** [comment]
ah but it is... sort of. it counts minor versions below 2 as 1, and major versions above 2 as 1, that way if someone is on version 1.1 they should still get a reading of 6 behind, which seems reasonable as prior to now our minor versions were often more like majors
